  steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'us-east1-docker.pkg.dev/einfo2024/services/devops-image-25786:$COMMIT_SHA', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'us-east1-docker.pkg.dev/einfo2024/services/devops-image-25786:$COMMIT_SHA']
      timeout: 2400s    
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['run', 'deploy', 'devops-25786', '--image', 'us-east1-docker.pkg.dev/einfo2024/services/devops-image-25786:$COMMIT_SHA', '--region', 'us-central1']
  images:
    - 'us-east1-docker.pkg.dev/einfo2024/services/devops-image-25786'
  options:
    logging: CLOUD_LOGGING_ONLY  
    